_target_: optax.join_schedules
schedules:
  - _target_: optax.linear_schedule
    init_value: 0.0
    end_value: 1.0
    transition_steps: ${warmup_steps}
  - _target_: optax.cosine_decay_schedule
    init_value: 1.0
    decay_steps: ${eval:${steps}-${warmup_steps}}
    alpha: 0.0
  
boundaries:
  - ${warmup_steps}